"""core: self-hosted evolutionary program-search engine.

Portions derived from SakanaAI/ShinkaEvolve (Apache-2.0); see NOTICE and
per-file headers for provenance. Naming is independent (docs/naming_map.md).
"""

from .checkpoint import atomic_write_json, config_fingerprint, load_json
from .config import PopulationConfig, ProposalConfig, SearchConfig
from .agent import (
    AgentBackend,
    AgentEvent,
    AgentEventKind,
    AgentSessionLimits,
    AgentSessionProposer,
    AgentSessionRequest,
    AgentSessionResult,
    AgentTermination,
    ConversationalAgentBackend,
    EventSink,
    EventSinkFactory,
    JsonlEventSink,
    JsonlEventSinkFactory,
    ManagedEventSink,
    NativeToolAgentBackend,
    PreflightTraceRecord,
    ProposalTraceSummary,
    TRANSCRIPT_SCHEMA_VERSION,
    TokenEstimator,
    render_workspace_patch,
)
from .preflight import (
    PreflightContext,
    PreflightIssue,
    PreflightPipeline,
    PreflightReport,
    PreflightResult,
    PreflightValidator,
    ProposalCheckResult,
    ProposalPreflight,
)
from .interfaces import (
    BudgetLike,
    Grader,
    LoopObserver,
    MutationContext,
    NullBudget,
    PromptContributor,
    RejectionEvent,
    RejectionObserver,
    SamplingWeightPolicy,
)
from .llm import (
    LLMClient,
    LLMMessage,
    LLMProtocolError,
    LLMResponse,
    LLMStopReason,
    LLMRateLimitError,
    LLMBillingError,
    LLMTransientError,
    LLMToolCall,
    LLMToolChoice,
    LLMToolChoiceMode,
    LLMToolDefinition,
    LLMToolResult,
    LLMTransport,
    make_openai_compat_transport,
)
from .loop import RunReport, SearchLoop
from .metrics import MetricLog, MetricPoint, flatten
from .novelty import GateVerdict, NoveltyGate, cosine_similarity
from .operators import (
    PatchEngine,
    PatchOutcome,
    PromptBuilder,
    apply_rewrite,
    editable_ranges,
    sample_operator,
    validate_edit_markers,
)
from .population import Candidate, IslandView, EvalReport, PopulationStore
from .proposer import (
    HybridProposalSelector,
    Proposal,
    ProposalLane,
    ProposeResult,
    Proposer,
    SingleShotProposer,
)
from .remote import (
    EvalInfraError,
    EvalProtocolError,
    RemoteEvalConfig,
    RemoteGrader,
    idempotency_key,
)
from .routing import BanditRouter, ModelRouter, StaticRouter
from .selection import (
    BeamSelector,
    InspirationSelector,
    LatestSelector,
    ParentSelector,
    PowerLawSelector,
    SeedOnlySelector,
    WeightedSelector,
    make_parent_selector,
)

__all__ = [
    "AgentBackend",
    "AgentEvent",
    "AgentEventKind",
    "AgentSessionLimits",
    "AgentSessionProposer",
    "AgentSessionRequest",
    "AgentSessionResult",
    "AgentTermination",
    "ConversationalAgentBackend",
    "EventSink",
    "EventSinkFactory",
    "JsonlEventSink",
    "JsonlEventSinkFactory",
    "ManagedEventSink",
    "NativeToolAgentBackend",
    "PreflightTraceRecord",
    "ProposalTraceSummary",
    "BanditRouter",
    "BeamSelector",
    "BudgetLike",
    "Candidate",
    "IslandView",
    "EvalReport",
    "GateVerdict",
    "Grader",
    "HybridProposalSelector",
    "InspirationSelector",
    "LLMClient",
    "LLMMessage",
    "LLMProtocolError",
    "LLMResponse",
    "LLMStopReason",
    "LLMRateLimitError",
    "LLMBillingError",
    "LLMTransientError",
    "LLMToolCall",
    "LLMToolChoice",
    "LLMToolChoiceMode",
    "LLMToolDefinition",
    "LLMToolResult",
    "LLMTransport",
    "LatestSelector",
    "LoopObserver",
    "MetricLog",
    "MetricPoint",
    "ModelRouter",
    "MutationContext",
    "NoveltyGate",
    "NullBudget",
    "ParentSelector",
    "PatchEngine",
    "PatchOutcome",
    "PopulationConfig",
    "ProposalConfig",
    "PopulationStore",
    "PowerLawSelector",
    "PreflightContext",
    "PreflightIssue",
    "PreflightPipeline",
    "PreflightReport",
    "PreflightResult",
    "PreflightValidator",
    "PromptBuilder",
    "PromptContributor",
    "Proposal",
    "ProposalLane",
    "ProposeResult",
    "Proposer",
    "RejectionEvent",
    "RejectionObserver",
    "SingleShotProposer",
    "RunReport",
    "SamplingWeightPolicy",
    "SearchConfig",
    "SearchLoop",
    "SeedOnlySelector",
    "StaticRouter",
    "TokenEstimator",
    "TRANSCRIPT_SCHEMA_VERSION",
    "WeightedSelector",
    "apply_rewrite",
    "atomic_write_json",
    "config_fingerprint",
    "cosine_similarity",
    "editable_ranges",
    "flatten",
    "load_json",
    "make_openai_compat_transport",
    "make_parent_selector",
    "sample_operator",
    "validate_edit_markers",
    "render_workspace_patch",
    "ProposalCheckResult",
    "ProposalPreflight",
]
